import XCTest
@testable import Nexus

final class LuaConfigTests: XCTestCase {
    private func writeTemp(_ contents: String) throws -> String {
        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("nexus-\(UUID().uuidString).lua")
        try contents.write(to: url, atomically: true, encoding: .utf8)
        return url.path
    }

    func testRoundTripPreservesConfig() throws {
        var original = Config()
        original.font.family = "JetBrains Mono"
        original.font.size = 15
        original.font.lineHeight = 1.35
        original.window.opacity = 0.8
        original.window.blur = true
        original.window.transparentTerminal = false
        original.theme.background = "#101010"

        let path = try writeTemp(LuaConfig.serialize(original))
        let loaded = try LuaConfig.load(path: path)
        XCTAssertEqual(loaded, original)
    }

    func testBuilderStyleConfig() throws {
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.font_family = "JetBrains Mono"
        config.font_size = 20
        config.opacity = 0.9
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.font.family, "JetBrains Mono")
        XCTAssertEqual(config.font.size, 20)
        XCTAssertEqual(config.window.opacity, 0.9, accuracy: 0.001)
    }

    func testRequireNexusAlsoWorks() throws {
        let path = try writeTemp(#"""
        local nexus = require 'nexus'
        local config = nexus.config()
        config.font_size = 18
        return config
        """#)
        XCTAssertEqual(try LuaConfig.load(path: path).font.size, 18)
    }

    func testPartialConfigFallsBackToDefaults() throws {
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.font_size = 16  -- only size set
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.font.size, 16)
        XCTAssertEqual(config.font.family, "SF Mono")       // default
        XCTAssertEqual(config.theme, Theme.defaultDark)      // default
        XCTAssertEqual(config.window.opacity, 1.0)           // default
    }

    func testLuaLogicIsAllowed() throws {
        // The whole point: users can compute values.
        let path = try writeTemp(#"""
        local base = 12
        local config = nexus.config()
        config.font_size = base + 2
        config.opacity = 82 / 100
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.font.size, 14)
        XCTAssertEqual(config.window.opacity, 0.82, accuracy: 0.001)
    }

    func testOldNestedFormatStillLoads() throws {
        // Files generated by the earlier nested format must not lose settings.
        let path = try writeTemp(#"""
        return {
          font = { family = "Menlo", size = 15, lineHeight = 1.3 },
          window = { opacity = 0.7, blur = true },
          theme = { background = "#101010" },
        }
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.font.family, "Menlo")
        XCTAssertEqual(config.font.size, 15)
        XCTAssertEqual(config.font.lineHeight, 1.3, accuracy: 0.001)
        XCTAssertEqual(config.window.opacity, 0.7, accuracy: 0.001)
        XCTAssertTrue(config.window.blur)
        XCTAssertEqual(config.theme.background, "#101010")
    }

    func testNamedThemeLoads() throws {
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.theme = "Nord"
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.theme, BuiltInThemes.named("Nord")?.theme)
    }

    func testRosePineByPlainName() throws {
        // Diacritic-insensitive: "rose pine" resolves to "Rosé Pine".
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.theme = "rose pine"
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.theme, BuiltInThemes.named("Rosé Pine")?.theme)
        XCTAssertEqual(config.theme.background, "#191724")
    }

    func testExplicitColorOverridesNamedTheme() throws {
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.theme = "Nord"
        config.background = "#000000"
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.theme.background, "#000000")               // override
        XCTAssertEqual(config.theme.foreground, BuiltInThemes.named("Nord")?.theme.foreground) // from Nord
    }

    func testKeybindingsMergeOntoDefaults() throws {
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.keybindings = { newTab = "cmd+shift+t" }
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.keybindings["newTab"], "cmd+shift+t")      // overridden
        XCTAssertEqual(config.keybindings["closePane"], "cmd+w")         // default kept
        XCTAssertEqual(config.keybindings["splitVertical"], "cmd+shift+d")
    }

    func testSerializeUsesThemeNameAndOmitsDefaultKeybindings() {
        let text = LuaConfig.serialize(Config())
        XCTAssertTrue(text.contains(#"config.theme = "One Dark""#))
        XCTAssertFalse(text.contains("config.ansi"))                 // no color dump
        XCTAssertFalse(text.contains("\nconfig.keybindings = {"))    // no active block (comment aside)
    }

    func testSerializeWritesCustomPaletteAndOverrides() {
        var config = Config()
        config.theme.background = "#010203"        // no longer a preset
        config.keybindings["newTab"] = "cmd+shift+t"
        let text = LuaConfig.serialize(config)
        XCTAssertTrue(text.contains("config.ansi"))
        XCTAssertTrue(text.contains(##"config.background = "#010203""##))
        XCTAssertTrue(text.contains("config.keybindings = {"))
        XCTAssertTrue(text.contains(#"newTab = "cmd+shift+t""#))
    }

    func testSidebarWidthRoundTripsAndClamps() throws {
        var original = Config()
        original.sidebarWidth = 420
        let path = try writeTemp(LuaConfig.serialize(original))
        XCTAssertEqual(try LuaConfig.load(path: path).sidebarWidth, 420)

        // Out-of-range values are clamped on load.
        let clampedPath = try writeTemp(#"""
        local config = nexus.config()
        config.sidebar_width = 9000
        return config
        """#)
        XCTAssertEqual(try LuaConfig.load(path: clampedPath).sidebarWidth, 680)
    }

    func testSyntaxErrorThrows() throws {
        let path = try writeTemp("local config = nexus.config(")  // truncated
        XCTAssertThrowsError(try LuaConfig.load(path: path))
    }

    func testOpacityClampedOnLoad() throws {
        let path = try writeTemp(#"""
        local config = nexus.config()
        config.opacity = 5.0
        return config
        """#)
        let config = try LuaConfig.load(path: path)
        XCTAssertEqual(config.window.opacity, 1.0, accuracy: 0.001)
    }
}
